-- Seed SINTÉTICO, só para desenvolvimento local e CI. Nunca aplicar em ambiente remoto.
--
-- Os municípios reais (João Pessoa 2507507, Cabedelo 2503209, limites do IBGE)
-- vêm da migration 20261001185320_report_write_path.sql, em todos os ambientes.
-- Os retângulos sintéticos que existiam aqui foram removidos para não conflitar
-- com o `unique (ibge_code)`. Os testes pgTAP usam fixtures próprias.
